
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: RailsTalk_development
test:
  <<: *default
  database: RailsTalk_test

production:
  <<: *default
  database: RailsTalk_production
  username: RailsTalk
  password: <%= ENV['RAILSTALK_DATABASE_PASSWORD'] %>
